### ISSUE TITLE
Instruct people on how to change the default viewer in RStudio

### ISSUE THREAD

**Issue by NeuroShepherd** [lmu-osc/introduction-to-Quarto#10]
For some people, the default is a new browser tab and for others its the Viewer pane in RStudio. We probably want people to default to the Viewer pane, and should provide instructions.

**Comment by NeuroShepherd** [comment]
This issue is likely also relevant to the intended Tips & Tricks tutorial

**Comment by NeuroShepherd** [comment]
Looks like this already exists in the Tips and Comments section, but should go further up in the tutorial. We had >5 participants ask about this while trying to do the tutorial exercises

**Comment by FlorianPargent** [comment]
I am not sure where to move this. I will keep it at the current position for now, but I have added a bit more text in [22d2d16](https://github.com/lmu-osc/introduction-to-Quarto/commit/22d2d16cc24260f719f3933f6951e986acc79cc2)
