### ISSUE TITLE
For some reason, every link appears as external link

### ISSUE THREAD

**Issue by fkohrt** [lmu-osc/introduction-to-Quarto#3]
Every time I click anywhere on the website, it opens up another tab

**Comment by FlorianPargent** [comment]
Yes, I also noticed this annoying behavior. I have included the link-external-filter yaml option described here (https://quarto.org/docs/reference/formats/html.html#links) but I probably made some mistake.

**Comment by fkohrt** [comment]
Fixed with dbb0f7a
