### ISSUE TITLE
Migrate repo to LMU OSC

### ISSUE THREAD

**Issue by NeuroShepherd** [lmu-osc/introduction-to-Quarto#4]
Hey Florian, @MalikaIhle mentioned that you had agreed to transfer ownership of this repo directly to the LMU OSC organization. If that's correct, this [page](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) details the steps. 

I can take care of redeploying the GitHub Pages site after that!

**Comment by FlorianPargent** [comment]
Sorry that I forgot to transfer the repo. I did now transfer ownership of this repo as well as the companion repos *myquartomanuscript* and *mywebr* that are used in the advanced exercises part of the tutorial. You can rename/restructure all repos as you see fit. Just tell me at some point in which repo I should commit any upcoming changes for the workshop used in the lmu-osc summer school 2024.

**Comment by NeuroShepherd** [comment]
Repo migrated!

**Comment by FlorianPargent** [comment]
Hi Pat, thanks for migrating the main repo of the quarto workshop. I have also transferred the two companion repos https://github.com/lmu-osc/mywebr and https://github.com/lmu-osc/myquartomanuscript. This broke the websites for both repos (and perhaps some links). Could you also have a look at that? Thanks!

**Comment by NeuroShepherd** [comment]
Websites are live and links have been updated! Feel free to reopen if I missed something.
