### ISSUE TITLE
Use CC-BY-SA license

### ISSUE THREAD

**Issue by NeuroShepherd** [lmu-osc/introduction-to-Quarto#7]
@MalikaIhle should we change the repo license to match with our standard for other repos?

**Comment by MalikaIhle** [comment]
I don't know, it seems they thought about it: https://lmu-osc.github.io/introduction-to-Quarto/about.html 
probably fine to keep that way!

**Comment by NeuroShepherd** [comment]
https://creativecommons.org/publicdomain/zero/1.0/

> The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.
> You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. See Other Information below.

Plus there is no note about attributing the original work to the authors, whereas CC-BY-SA allows sharing and adaptation but requests attribution to the original authors. @FlorianPargent @fkohrt was there a special motivation for using the CC0 license?

**Comment by fkohrt** [comment]
Well, it's primarily a question of permissive vs. copyleft licenses, and both have their pros and cons. I tend to use permissive licenses for things that are not terribly original or unique. And not to devalue the time we have spent creating this tutorial, but openly licensed Quarto introductions are already ubiquitous, so I don't see any value in putting restrictions on this one. Should this be cited in academic literature, attribution is already required regardless of copyright status. Also, [CC0's statement of purpose](https://creativecommons.org/publicdomain/zero/1.0/legalcode#sop) is just delightful.

> These owners may contribute to the Commons to promote the ideal of a free culture and the further production of creative, cultural and scientific works, or to gain reputation or greater distribution for their Work in part through the use and efforts of others.

**Comment by NeuroShepherd** [comment]
Sounds good! Will leave the license alone and close this issue.
