### ISSUE TITLE
Tricky inline computations

### ISSUE THREAD

**Issue by fkohrt** [lmu-osc/introduction-to-Quarto#9]
I feel like participants are bound to trip over instances of quarto-dev/quarto-cli#10595. Should we add the peculiarities of using `` `{r} ...` `` under _possible problems_? Or directly recommend using `` `r ...` ``?

**Comment by FlorianPargent** [comment]
In commit [1fcd417](https://github.com/lmu-osc/introduction-to-Quarto/commit/1fcd41741ba729ef40dd97563616de0e36e3312e) I have added a comment to the relevant section that we recommend `` `r ...` ``, briefly mention the most important difference and link to the inline code documentation.
